export const RESUME_LANGUAGE_CODES = [
  { code: "amh", name: "Amharic" },
  { code: "arb", name: "Arabic" },
  { code: "azj", name: "North Azerbaijani" },
  { code: "ben", name: "Bengali" },
  { code: "bho", name: "Bhojpuri" },
  { code: "bos", name: "Bosnian" },
  { code: "bul", name: "Bulgarian" },
  { code: "ces", name: "Czech" },
  { code: "cmn", name: "Mandarin Chinese" },
  { code: "ckb", name: "Central Kurdish" },
  { code: "deu", name: "German" },
  { code: "ell", name: "Greek" },
  { code: "eng", name: "English" },
  { code: "fra", name: "French" },
  { code: "fuv", name: "Nigerian Fulfulde" },
  { code: "guj", name: "Gujarati" },
  { code: "hau", name: "Hausa" },
  { code: "heb", name: "Hebrew" },
  { code: "hin", name: "Hindi" },
  { code: "hrv", name: "Croatian" },
  { code: "hun", name: "Hungarian" },
  { code: "ibo", name: "Igbo" },
  { code: "ilo", name: "Iloko" },
  { code: "ind", name: "Indonesian" },
  { code: "ita", name: "Italian" },
  { code: "jav", name: "Javanese" },
  { code: "jpn", name: "Japanese" },
  { code: "kan", name: "Kannada" },
  { code: "kaz", name: "Kazakh" },
  { code: "kin", name: "Kinyarwanda" },
  { code: "kor", name: "Korean" },
  { code: "lin", name: "Lingala" },
  { code: "mag", name: "Magahi" },
  { code: "mai", name: "Maithili" },
  { code: "mal", name: "Malayalam" },
  { code: "mar", name: "Marathi" },
  { code: "mya", name: "Burmese" },
  { code: "nld", name: "Dutch" },
  { code: "npi", name: "Nepali" },
  { code: "nya", name: "Nyanja" },
  { code: "pes", name: "Iranian Persian" },
  { code: "pbu", name: "Northern Pashto" },
  { code: "pol", name: "Polish" },
  { code: "por", name: "Portuguese" },
  { code: "ron", name: "Romanian" },
  { code: "rus", name: "Russian" },
  { code: "run", name: "Rundi" },
  { code: "sin", name: "Sinhala" },
  { code: "skr", name: "Saraiki" },
  { code: "som", name: "Somali" },
  { code: "spa", name: "Spanish" },
  { code: "sun", name: "Sundanese" },
  { code: "swe", name: "Swedish" },
  { code: "tam", name: "Tamil" },
  { code: "tel", name: "Telugu" },
  { code: "tha", name: "Thai" },
  { code: "tgl", name: "Tagalog" },
  { code: "tur", name: "Turkish" },
  { code: "ukr", name: "Ukrainian" },
  { code: "urd", name: "Urdu" },
  { code: "uzn", name: "Northern Uzbek" },
  { code: "vie", name: "Vietnamese" },
  { code: "yor", name: "Yoruba" },
  { code: "zlm", name: "Malay" },
  { code: "zul", name: "Zulu" },
];
